### ISSUE TITLE
关于 HEXO 与 语雀兼容

### ISSUE THREAD

**Issue by cryzlasm** [x-cold/yuque-hexo#1]
今天发现了语雀这个平台, 发现他的编辑器真的使用方便, 
目前来说, 个人感觉没有任何一个MD编辑器能比得过它 
然后自己有使用基于GITPage 的HEXO博客,
想咨询一下, 这个能直接跟原有的hexo博客兼容么?
(个人对前端不是太懂)

比如:   
语雀编辑结束, 进行发布之后, 
这边HEXO 敲入一个命令 自动同步MD到本地,  (这一块 好像是您这当前项目的功能)
然后自动生成博客同步到GIT (这个功能HEXO自带)

问题重点:  会不会清空已有的数据?

**Comment by x-cold** [comment]
只会清空 yuque 目录下的文章，只需要把 yuque 编辑的文章放到特定的目录(_posts/yuque/)，其他目录不受影响

**Comment by cryzlasm** [comment]
好的, 谢谢, 我先试试, 有问题再来咨询
