### ISSUE TITLE
nodejs16.13.1无法正常同步

### ISSUE THREAD

**Issue by tangyuanpro** [x-cold/yuque-hexo#100]
nodejs16.13.1同步时报错，已经使用的是yuque-hexo在npm上的最新版
[ERROR] invalid post: [object Object]
⚠️  TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1640956243350)
⚠️  Command Error, enable `DEBUG=common-bin` for detail
![IMG_20211231_211329](https://user-images.githubusercontent.com/46566057/147825276-4b9eb21c-40a7-4869-bafd-666ea6054aff.jpg)

**Comment by x-cold** [comment]
升级到最新版本试试，看上去是文档有问题，可以发一下链接吗

**Comment by tangyuanpro** [comment]
> 升级到最新版本试试，看上去是文档有问题，可以发一下链接吗

可以的
https://www.yuque.com/yexiyingla/lianyou/gh034r

**Comment by x-cold** [comment]
问题解决了吗

**Comment by tangyuanpro** [comment]
目前没有用hexo了，谢谢关心
