### ISSUE TITLE
生成的文档名称为随机数？

### ISSUE THREAD

**Issue by Mister24** [x-cold/yuque-hexo#102]
readme中说的
“语雀同步过来的文章会生成两部分文件；

yuque.json: 从语雀 API 拉取的数据
source/_posts/yuque/*.md: 生成的 md 文件
”

遇到的问题：
1. 没有yuque.json
2. 路径不对，且名称为随机【实际只是看到了 source/_posts/xxx.md source/_posts/yyyy.md  生成的文件名称是随机的6位数字字母组合】

**Comment by x-cold** [comment]
看下是否为 mdNameFormat 配置成 slug 了
https://github.com/x-cold/yuque-hexo#%E9%85%8D%E7%BD%AE%E7%9F%A5%E8%AF%86%E5%BA%93
