### ISSUE TITLE
yuque-hexo sync生成的文件里字符数字前多了空格

### ISSUE THREAD

**Issue by Lawliet99** [x-cold/yuque-hexo#103]
yuque-hexo sync  生成的文件里字符数字前多了空格
![image](https://user-images.githubusercontent.com/63592085/148826042-357d9304-ef4b-4fbe-8ab9-879b135fe80e.png)
语雀原本的没有空格   生成之后多了空格  这怎么解决呢

**Comment by Lawliet99** [comment]
英文字母跟数字  前后都会产生空格

**Comment by ql-isaac** [comment]
加空格好看些啊，这个是被格式化了

**Comment by x-cold** [comment]
这个是语雀自动处理的格式，暂时没法调整，整体来说书写风格反而更合理了
