### ISSUE TITLE
imgCdn设置true后设置cos或者oss都没有替换图片，加debug也没什么信息吐出，感觉没触发替换程序

### ISSUE THREAD

**Issue by jifuwei** [x-cold/yuque-hexo#118]

**Comment by jifuwei** [comment]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/16236899/188188258-2e8eb690-4304-4479-9498-df1b062f43c6.png">

**Comment by jifuwei** [comment]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/16236899/188188769-4d6617e9-33df-4663-ade3-00cc44dbd4a4.png">

**Comment by i1mT** [comment]
我这里也出现了这个问题

**Comment by LetTTGACO** [comment]
升级到最新版1.9.4试一下，新版增加了log日志，可以看一下错误出在哪里

**Comment by jifuwei** [comment]
其实不是bug, 因为之前同步过文章，是按照文章是否更新来触发图片加载的，执行 clean 命令，可以清楚本地文章再同步一次即可
