### ISSUE TITLE
用七牛云上传图片，但是图片损坏了，不知道那里出问题了

### ISSUE THREAD

**Issue by xyokei** [x-cold/yuque-hexo#122]
这是上传到七牛云的图片，都变成311 B大小了，访问外链都是空白的小方块
![image](https://user-images.githubusercontent.com/115436563/195996219-d5e36328-509e-4bab-9762-80fa8835b690.png)

日志里也没报错
![image](https://user-images.githubusercontent.com/115436563/195996281-0b071282-426a-4bbc-aa62-14d4adaa1bf4.png)

**Comment by bazijun** [comment]
我也遇到这个问题，有些图片可以。有些又不行。

**Comment by xyokei** [comment]
我想应该是图片上传时损坏了，就在本地找到作者上传图片的地方，加一行输出下获得图片时的数据是啥
![image](https://user-images.githubusercontent.com/115436563/196169562-7f70dba3-4d11-40b8-abaa-6a3ccf36ed4d.png)
**跑出来 是下面这个错误**
![image](https://user-images.githubusercontent.com/115436563/196170391-23a5d342-6c5b-4488-afd7-6b8a190a3546.png)
百度了下，**403 Forbidden**  要加个用户代理，就尝试了下，就突然好了
![image](https://user-images.githubusercontent.com/115436563/196171278-19cae479-6fe0-4e88-9691-038775b835fc.png)
跑完七牛云图片正常了
![image](https://user-images.githubusercontent.com/115436563/196171679-f437c0ec-ac01-4ef3-b5af-b2d011cefdc6.png)
不知道是不是只有七牛云有这个问题，还是三个都有，@x-cold @LetTTGACO 大佬看看 能更新下这个bug吗？

**Comment by LetTTGACO** [comment]
感谢，确实没考虑这种情况，稍后测试完成后更新

**Comment by LetTTGACO** [comment]
已解决，升级到1.9.2即可

**Comment by xyokei** [comment]
> 已解决，升级到1.9.2即可

试过了，图片正常出来了，感谢~

**Comment by ql-isaac** [comment]
腾讯云也有这种问题，我等下试下
