### ISSUE TITLE
可以自动上传到又拍云 图床么

### ISSUE THREAD

**Issue by Leader755** [x-cold/yuque-hexo#123]

**Comment by LetTTGACO** [comment]
图床需求太多了，欢迎自己实现后提mr
图床的实现可以参考这个文章[《yuqe-hexo插件支持多图床》](https://www.yuque.com/docs/share/d243a36d-9b4c-4e6d-804d-8a40678c6fea?# )

**Comment by LetTTGACO** [comment]
已支持Github图床和又拍云图床，升级到1.9.4即可
