### ISSUE TITLE
语雀图片转换失败

### ISSUE THREAD

**Issue by jifuwei** [x-cold/yuque-hexo#124]
今天上传新的文章后，无法同步图片到图床，试了下cos 和 github 图片均无法上传，猜测是语雀端做了什么限制，大家有遇到么？

**Comment by LetTTGACO** [comment]
有具体的报错信息吗？

**Comment by LetTTGACO** [comment]
是我这边的改动问题，稍等我更新一下

**Comment by LetTTGACO** [comment]
已更新到1.9.5版本
- 修复腾讯云图床/Github图床上传问题
- 图片上传失败时，取消停止进程
- 新增图片上传时的并发数concurrency，使用Github图床时，并发问题严重，建议设置为1
