### ISSUE TITLE
关于  adpater (hexo) is invalid. 的问题

### ISSUE THREAD

**Issue by k3lpi3b4nsh33** [x-cold/yuque-hexo#131]
![image](https://user-images.githubusercontent.com/118002757/202843320-d899077c-832f-44e6-9cd6-a788795319c6.png)

已经下载了 yuque.json，但是他无法上传到 阿里云图床，报错如上图。
你好，请问这应该怎么解决呢？

**Comment by LetTTGACO** [comment]
yuqueConfig 的配置发一下

**Comment by k3lpi3b4nsh33** [comment]
![image](https://user-images.githubusercontent.com/118002757/202844628-9edea82e-f26e-4a56-b209-331d384fae23.png)

**Comment by LetTTGACO** [comment]
首先，保证你的yuque-hexo的版本为1.9.5，如果不是的话，请升级到这个版本，如果还有问题

需要你找到你项目的node_modules中的yuque-hexo源码，在lib/Downloader.js的211行加上log看一下问题出在哪里？
![image](https://user-images.githubusercontent.com/37357188/202844898-09593e5d-3673-46c1-98fb-989e7cf820ad.png)

**Comment by k3lpi3b4nsh33** [comment]
![image](https://user-images.githubusercontent.com/118002757/202845667-2a010024-eea0-413f-a72a-8583b705539d.png)
你好，我是在window10環境下，我應該怎麽修改才能添加 accessKeyId, accessKeySecret呢?

**Comment by LetTTGACO** [comment]
本地跑的话，看这个示例，安装dotenv-cli，并且新建.env文件，将环境变量写入即可
https://github.com/LetTTGACO/yuque-hexo-example/blob/master/package.json

**Comment by LetTTGACO** [comment]
你的语雀token也建议写到.env文件，不要写入yuqueConfig中

**Comment by LetTTGACO** [comment]
线上部署时，如果使用github action进行部署，则可以使用自带的secret来配置环境变量，其他的部署工具也有类似的环境变量设置

**Comment by k3lpi3b4nsh33** [comment]
以成功解决，谢谢你的帮助。祝你有一个好周末

**Comment by k3lpi3b4nsh33** [comment]
你好，在进行线上部署的时候，secret 已经配置好，但是还是会出错。出错和 adpater (hexo) is invalid 一样。我应该怎么修改呢？

![image](https://user-images.githubusercontent.com/118002757/202886436-f466d96e-f882-49ac-a490-9199d6f10ca7.png)


`name: Deploy Hexo Public To Pages

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repositrory master brach
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g
          npm install yuque-hexo -g
      - name: Cache
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - name: Install another software
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          export TZ='Asia/Shanghai'
          npm install
          wget https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64              
          wget https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz
          tar zxvf aliyun-cli-linux-latest-amd64.tgz
          chmod 777 ossutil64
          sudo cp aliyun /usr/local/bin
          sudo cp ossutil64 /usr/local/bin
      - name: SET env value
        env:
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ${{ secrets.REGION }}
        run: |
          ossutil64 config -i $SECRET_ID -k $SECRET_KEY -e $REGION -c /home/runner/.ossutilconfig
          ossutil64 stat oss://$BUCKET
          aliyun configure set --profile akProfile --mode AK --region cn-hangzhou --access-key-id $SECRET_ID --access-key-secret $SECRET_KEY
          
          ## 用的是阿里云 OSS，但是我不是很会配置。

      - name: pull the articles from yuque 
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
        run: |
          npm run yuque:clean
          npm run yuque:sync
      - name: Set git config username and email
        run: |
          git config --global user.name "l3vi4th4n"
          git config --global user.email "********"
      - name: Send the articles to Github Pages
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
          git add .
          git commit -m "Refresh yuque json" -a
      - name: push to repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Static files
        run: |
          npm run hexo:build
`


![image](https://user-images.githubusercontent.com/118002757/202886544-a6f2f407-0e89-417c-baeb-474fcfbc7516.png)

**Comment by LetTTGACO** [comment]
![image](https://user-images.githubusercontent.com/37357188/202886839-a3517163-aba9-4040-9934-aa315fb1785e.png)
如果只是使用阿里云的图床，那应该在这里配置
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
你在上面配置阿里云的密钥是为了将hexo部署到阿里云吗？

**Comment by k3lpi3b4nsh33** [comment]
由于我不会 git action，今天恶补了一下知识，目前已经能够上传到博客，谢谢你。
