### ISSUE TITLE
是否可以保留hexo写博客的能力？

### ISSUE THREAD

**Issue by jayying007** [x-cold/yuque-hexo#135]
目前这个插件会把hexo所有文章清空，然后拉取语雀的文档，如果我原先有hexo的文章，那这部分就会丢失了（除非我把这部分内容写到语雀文档上）。
是不是可以在hexo里面留一个文件夹专门存放用hexo写的文章，然后发布时将这部分和语雀的合并。

**Comment by jayying007** [comment]
看起来好像不使用yuque-hexo clean就行

**Comment by codeskyblue** [comment]
我看了下默认会把source/_posts/yuque
目录清空，其他的还会保留着

**Comment by x-cold** [comment]
yuque-hexo clean 只会清空 postPath 目录，这个是可以自定义配置的（默认是 source/_posts/yuque），可以跟你手动写 hexo 文章的目录（例如 source/_posts/custom）区分一下，不会影响到正常写 hexo 文章。
