### ISSUE TITLE
语雀开放 Webhook 了，建议可以集成一个 Server 模式暴露给语雀

### ISSUE THREAD

**Issue by xenv** [x-cold/yuque-hexo#16]
建议可以类似 hexo s 一样运行一个 Node Web Server，然后给出一个地址，用户直接在 Webhook 里面填服务器的更新地址就可以直接同步更新啦。

新版文档：https://www.yuque.com/yuque/developer/doc-webhook

**Comment by x-cold** [comment]
I see see

**Comment by lweein** [comment]
up up up

**Comment by x-cold** [comment]
Server 模式可以提供两种方式去实现

1、中心化方案，提供一个专门用于「文档转换」服务的集中 Http Server
2、端的方案，开发过程中在本地开启 HTTP Server，通过内网穿透让语雀可访问

对于方案 1 我认为需求和投入可能需要仔细考量一下，需要考虑的东西非常多，比如怎么保障服务稳定运行，如何更好地提供服务等等。

方案 2 我个人感觉是比较鸡肋的，如果说只是为了在开发环境同步文档，完全可以通过定时任务去执行，cli 层面我已经做了一层缓存，所以成本上来说并不高。

以上，短期内可能不会去做一个 webhook 的支持，不过还是想听听你们的想法

@xenv 你觉得这个东西搞成怎么样合适呢。

**Comment by xenv** [comment]
@x-cold 
中心化方案投入有点高，现在用的人还太少。

所以应该是端的方案比较好，现在有 WebHook 的话还是比定时方便一些，如果不弄的话，我自己用 web.py 执行下 npm ，应该十几行就搞定了。透传确实是个问题，不过也可以放在公网的机器上面自动执行呀。反正那个文件夹不用改。

还有一种思路是，Serverless 云函数，用 Serverless 的触发器，不过好像阿里云和腾讯云对 node 的支持还不太好，还要配合 OSS 这类的玩意。 Amazon 的不太清楚。还有普通 CI 不知道有没有定制化强一些的。

**Comment by lweein** [comment]
@xenv 我刚开始接触hexo和语雀，我想走的方式是，使用语雀的文章更新的webhook，通知到我的程序源代码coding 上，触发coding的持续构建+Jenkins服务，然后跑完build之后，再自动推送到COS+CDN 和Github上进行发布。

这样的方式可行么？我自己还没开始尝试。本来是想用Travis的，不过最近Coding 和腾讯云开发者平台合并，提供了持续构建服务，想试一试。

这样的话，依托于最新的语雀webhook，还是可以进行全自动部署。

**Comment by xenv** [comment]
@lweein
你可以试一下，应该是可行的。就是不知道有没有提供URL触发器
部署到 COS 用 hexo 的插件就可以。

**Comment by Ghostdar** [comment]
@lweein coding 的持续集成貌似还没有提供开放的API

**Comment by lweein** [comment]
> @lweein coding 的持续集成貌似还没有提供开放的API，顺便看了一下travis-ci 的 api，需要将身份验证令牌设置在header里：
> ![image](https://user-images.githubusercontent.com/17442718/50630449-eb9f7200-0f7b-11e9-88e2-e9fc1d553d87.png)
> 以上，目前语雀的webhook怕是无法构建这种请求。

是的。我后来也发现了。这样行不通。。。而且有个槽点。语雀编辑器对frontmatter 不好弄。hexo无法识别

**Comment by x-cold** [comment]
@Ghostdar 有空分享下你的 CI 方案呗

**Comment by Ghostdar** [comment]
@x-cold @lweein 这两天捣鼓了一下，粗糙的方案，能初步满足需求：https://segmentfault.com/a/1190000017797561

**Comment by lweein** [comment]
> @x-cold @lweein 这两天捣鼓了一下，粗糙的方案，能初步满足需求：https://segmentfault.com/a/1190000017797561

在语雀上看到你的文章了。写的很不错啊。回头我借鉴一下，也倒腾一个serverless ，语雀上聊

**Comment by xenv** [comment]
https://gist.github.com/xenv/8406f399d7df657895cd44028267556e

因为我的是直接在服务器上面放的博客，我现在就暂时在服务器跑这个执行下 npm，对外面暴露个端口

@Ghostdar 的也不错，就是文章多的话从头下载可能要一些时间，不过这个也没什么办法。

**Comment by Ghostdar** [comment]
@xenv 这个问题有想过，如果结合github 的 api 可以做到只更新webhook回调的文章，我还没深入研究，也是一种思路吧。

**Comment by youngjuning** [comment]
66666
