### ISSUE TITLE
语雀 markdown 编辑 tags、data、categories 这些信息，有多余的换行符导致解析不正确

### ISSUE THREAD

**Issue by Ghostdar** [x-cold/yuque-hexo#17]
![image](https://user-images.githubusercontent.com/17442718/50886416-50027b80-142b-11e9-830e-5dbb54b5a0a8.png)

![image](https://user-images.githubusercontent.com/17442718/50886491-77594880-142b-11e9-9c94-5f200bd60753.png)

感觉要做些兼容

**Comment by Tfrain** [comment]
萌新弱弱的问一句，问题已经解决了吗？怎么操作

**Comment by Ghostdar** [comment]
@Tfrain  解决了，已经提交了pr，等作者发布版本

**Comment by Tfrain** [comment]
> @Tfrain 解决了，已经提交了pr，等作者发布版本

已get，谢谢

**Comment by x-cold** [comment]
1.3.1
