### ISSUE TITLE
hexo g 会报错

### ISSUE THREAD

**Issue by aiokr** [x-cold/yuque-hexo#19]
hexo g报错 
![image](https://user-images.githubusercontent.com/25877104/51255162-a2b8d600-19dd-11e9-98ca-8285c0e6dcfd.png)

**Comment by x-cold** [comment]
玛法提供一下文章的内容和标题

**Comment by aiokr** [comment]
> 麻烦提供一下文章的内容和标题

https://www.yuque.com/docs/share/17a48131-d34e-45c8-8ac3-62d3593558fd

**Comment by x-cold** [comment]
这么看起来的话有点像是标题中含有非法字符，你试试配置成 slug 的路径模式，能否规避这个问题
