### ISSUE TITLE
语雀的meta信息只有第一行有效

### ISSUE THREAD

**Issue by Tfrain** [x-cold/yuque-hexo#20]
执行yuque-hexo sync之后报错
![2019-01-18 00-18-20](https://user-images.githubusercontent.com/39027451/51332515-d87dbd80-1ab6-11e9-82d0-8690e3b4234a.png)
tags: [Hexo]
categories: 教程
只有第一行tags起作用，如果categories在第一行则categories起作用
hexo的相关配置如下
![2019-01-18 00-27-12](https://user-images.githubusercontent.com/39027451/51333028-dff19680-1ab7-11e9-99e2-a69d5d0f773d.png)

**Comment by x-cold** [comment]
语雀最近更新了编辑器，应该是受到换行导致的问题，我周末研究一下
