### ISSUE TITLE
持续构建的时候出错了

### ISSUE THREAD

**Issue by lzq920** [x-cold/yuque-hexo#22]
![image](https://user-images.githubusercontent.com/37999725/51970812-caff0500-24b2-11e9-975f-cb178f5b69a2.png)

**Comment by imdingtalk** [comment]
我也遇到了 这样的问题，问题好像是随机出现的。这个是某个api对请求有限制么？  相同的构建，我第二天再去构建一次，又恢复正常了

**Comment by imdingtalk** [comment]
> 我也遇到了 这样的问题，问题好像是随机出现的。这个是某个api对请求有限制么？ 相同的构建，我第二天再去构建一次，又恢复正常了

![image](https://user-images.githubusercontent.com/16778873/51972101-a48e9900-24b5-11e9-8ddf-de5eb7370bd0.png)

**Comment by x-cold** [comment]
可能是构建机器的网络问题，这个错误是网络超时导致的。下个版本我把超时时间的配置也独立出来

**Comment by x-cold** [comment]
目前把超时时间设定为 30s 了
