### ISSUE TITLE
文章封面cover的问题

### ISSUE THREAD

**Issue by CasualMing** [x-cold/yuque-hexo#25]
在语雀上写了cover的路径，但是在同步的时候，会出现格式问题

**Comment by x-cold** [comment]
是专栏型的知识库吗？

**Comment by CasualMing** [comment]
是的呢，个人建的
![Uploading snipaste_201904
![snipaste_20190417_094330](https://user-images.githubusercontent.com/40878104/56254938-63da0f80-60f5-11e9-810d-ea52df1ee785.png)
17_094249.png…]()

**Comment by CasualMing** [comment]
是的呢，个人创建的
![snipaste_20190417_094249](https://user-images.githubusercontent.com/40878104/56255034-d4812c00-60f5-11e9-8afd-d9327ca22111.png)
![snipaste_20190417_094330](https://user-images.githubusercontent.com/40878104/56255048-e4990b80-60f5-11e9-85d7-22e249f4bf02.png)

**Comment by x-cold** [comment]
1.5.0 已修复，欢迎试用

**Comment by CasualMing** [comment]
cover在语雀上写了，但是同步不下来，不知为何，已经升级到最近版本了的
![snipaste_20190418_182820](https://user-images.githubusercontent.com/40878104/56355074-fd91e180-6207-11e9-8adc-8dbc16777ff5.png)
![snipaste_20190418_182905](https://user-images.githubusercontent.com/40878104/56355082-0387c280-6208-11e9-8f80-8393d136ae85.png)
