### ISSUE TITLE
还是cover的问题

### ISSUE THREAD

**Issue by CasualMing** [x-cold/yuque-hexo#26]
在语雀上正常写的cover，但是拉不下来

**Comment by x-cold** [comment]
yuque-hexo 更新到 1.5.0 了吗

**Comment by CasualMing** [comment]
更新到了
![snipaste_20190426_095538](https://user-images.githubusercontent.com/40878104/56778579-7c3ede00-6809-11e9-9320-445d4122e2cb.png)

**Comment by x-cold** [comment]
可以发一下带 cover 文章的相关信息吗？
语雀的链接，下载之后生成的内容

**Comment by CasualMing** [comment]
https://www.yuque.com/wuxintomgxue/nb/gbwkwa   // 这个是语雀上的
![snipaste_20190426_101543](https://user-images.githubusercontent.com/40878104/56779175-494a1980-680c-11e9-8870-3785eebb0805.png)
如果语雀上加上摘要，就成下面的这样
![snipaste_20190426_101716](https://user-images.githubusercontent.com/40878104/56779222-7eef0280-680c-11e9-8550-ce3a522ffd4a.png)

**Comment by x-cold** [comment]
分隔符有问题哦，只需要三个中划线就可以了

**Comment by CasualMing** [comment]
好，我试下

**Comment by CasualMing** [comment]
不是分隔符的问题啊。我试了一下修改成三个，拉下来的跟之前一样的
![snipaste_20190426_111655](https://user-images.githubusercontent.com/40878104/56781189-dee9a700-6814-11e9-96f4-ce582d35fe23.png)
![snipaste_20190426_111708](https://user-images.githubusercontent.com/40878104/56781226-09d3fb00-6815-11e9-90dd-9a65d62d970d.png)

**Comment by x-cold** [comment]
你看我这个分割线的效果

https://www.yuque.com/yinzhi/blog/gdquyk

**Comment by CasualMing** [comment]
我换了你那种分割线，效果还是跟之前一样的

**Comment by x-cold** [comment]
https://github.com/x-cold/yuque-hexo/issues/27#issuecomment-490138318

fix in v1.6.0

**Comment by TomatoFryEggs** [comment]
> [#27 (comment)](https://github.com/x-cold/yuque-hexo/issues/27#issuecomment-490138318)
> 
> fix in v1.6.0
请问为什么我1.6.2了还是会出现这个问题？

**Comment by TomatoFryEggs** [comment]
> > [#27 (comment)](https://github.com/x-cold/yuque-hexo/issues/27#issuecomment-490138318)
> > fix in v1.6.0
> > 请问为什么我1.6.2了还是会出现这个问题？
> > ![image](https://user-images.githubusercontent.com/9395814/68912204-64717c00-0792-11ea-8384-cd2abb85c2e1.png)

@x-cold
