### ISSUE TITLE
多标签显示错误

### ISSUE THREAD

**Issue by Aqpcet** [x-cold/yuque-hexo#31]
yuque-hexo sync后
多标签显示如下
![深度截图_选择区域_20190527234530](https://user-images.githubusercontent.com/20990883/58429934-08c70f80-80da-11e9-9948-39f73c49ca33.png)

hexo g
多标签显示如下
![深度截图_选择区域_20190527234643](https://user-images.githubusercontent.com/20990883/58429951-18465880-80da-11e9-93f6-c272cd51f11a.png)

部署后显示如下
![深度截图_选择区域_20190527234723](https://user-images.githubusercontent.com/20990883/58429970-24cab100-80da-11e9-9b09-e1748835d537.png)

拉取语雀的文章后的tags少了[ ]。

**Comment by x-cold** [comment]
版本是最新的吗

**Comment by Aqpcet** [comment]
是最新的1.6.0，我看到有其他人提交了解决代码，可能你需要合并一下。 @x-cold

**Comment by Aqpcet** [comment]
好的，谢谢

**Comment by x-cold** [comment]
v1.6.1
