### ISSUE TITLE
yuque中标题带冒号时hexo无法生成post的问题

### ISSUE THREAD

**Issue by icpz** [x-cold/yuque-hexo#32]
如题，请问可以配置在拉取后自动给title字段加上引号吗

**Comment by YUUtan1994** [comment]
同样碰上了，我是代码中被引入到description中了，求可以在语雀分割出description的方法

**Comment by x-cold** [comment]
这里加上引号会不会对 hexo 造成其他影响呢？

**Comment by lcdtyph** [comment]
我自己写了个自动加双引号的脚本，目前来看没什么影响。
就是如果标题中原来有双引号的话需要转义一下= =

**Comment by x-cold** [comment]
转义成什么值呢？我试过 html 实体字符也不行呢 &quot; &#34;
