### ISSUE TITLE
README 里配置多了 `/`

### ISSUE THREAD

**Issue by lengthmin** [x-cold/yuque-hexo#40]
![image](https://user-images.githubusercontent.com/13938334/62424560-cab22180-b702-11e9-8e2e-830fe5a49b3e.png)
![image](https://user-images.githubusercontent.com/13938334/62424585-28466e00-b703-11e9-93bb-f38032c8d8d4.png)

**Comment by x-cold** [comment]
欢迎 PR

**Comment by lengthmin** [comment]
🤣 修改了一点点文档
