### ISSUE TITLE
语雀 cdn 防盗链临时解决方案

### ISSUE THREAD

**Issue by x-cold** [x-cold/yuque-hexo#41]
临时方案是直接在 html 模版中添加 head 进行绕过

```html
<meta name="referrer" content="no-referrer" />
```

**Comment by anjia0532** [comment]
666,非常感谢分享

**Comment by liyatang** [comment]
优秀

**Comment by lsr911** [comment]
想问一下，html 模板是哪个文件？

**Comment by JohnieXu** [comment]
**通过img标签添加`referrerpolicy`属性可以解决**
```
<img width="120" height="120" src="https://cdn.nlark.com/yuque/0/2019/png/123320/1574751346300-cf918f18-6831-4bef-99e1-ae4d10e233cb.png" referrerpolicy="no-referrer">
```
效果如下：
<img width="120" height="120" src="https://cdn.nlark.com/yuque/0/2019/png/123320/1574751346300-cf918f18-6831-4bef-99e1-ae4d10e233cb.png" referrerpolicy="no-referrer">

**Comment by x-cold** [comment]
> 想问一下，html 模板是哪个文件？

这个要具体看对应主题的模板，一般来说都是 post.xxx

**Comment by maoziya** [comment]
<meta name="referrer" content="no-referrer" /> 加了这个不蒜子失效，冲突了，无语啊

**Comment by x-cold** [comment]
> 加了这个不蒜子失效，冲突了，无语啊

那你可以试试在图片输出的时候，参考楼上的方案，给 img 标签添加 referrerpolicy 属性

**Comment by Leader755** [comment]
对的，我之前也是遇到了这个问题，然后采用全局去**匹配文章中的图片**，给图片后面添加属性，但是有些浏览器是无效的。比如手机浏览器，pc上safiar浏览器，开启后chrome能正常展示。所以个人认为这个不是解决的办法。最好的解决的办法就是同步时，将图片进行base64转换或者转换使用自己的cdn链接，**问题在这个自动转换，对于我是有难度的。所以请各位大佬看看怎么处理=**。

**Comment by wxyhgk** [comment]
没什么用啊，只有谷歌浏览器可以搞，其他的都不行

**Comment by gaotuan** [comment]
<meta name="referrer" content="no-referrer" />  加在哪里？

**Comment by lonbaw** [comment]
> referrerpolicy="no-referrer"

background-image: url(https://cdn.nlark.com/yuque/0/2021/jpeg/1526841/1619860305167-0a13b77d-4397-490e-bba0-99b7bfb760c3.jpeg);  像这种引用 该怎么解决防盗的问题呢？

**Comment by xincao20** [comment]
> 临时方案是直接在 html 模版中添加 head 进行绕过
> 
> ```
> <meta name="referrer" content="no-referrer" />
> ```

默认的主题如何加入？好像没有找到对应的html模板

**Comment by LetTTGACO** [comment]
升级到1.9.0版本即可，目前支持腾讯云/阿里云/七牛云图床链接 替换 语雀链接

**Comment by lsr911** [comment]
你好！你的邮件我已经收到，我会尽快回复你的

**Comment by imleft** [comment]
> 升级到最新版本即可，目前支持腾讯云/阿里云/七牛云图床链接 替换 语雀链接

如果能支持S3,B2等就好啦

**Comment by lsr911** [comment]
你好！你的邮件我已经收到，我会尽快回复你的

**Comment by capdream** [comment]
请问有最新版的吗？加上head也无法显示

**Comment by lsr911** [comment]
你好！你的邮件我已经收到，我会尽快回复你的

**Comment by x-cold** [comment]
> 请问有最新版的吗？加上head也无法显示

可以开启工具 CDN 转存的功能

**Comment by capdream** [comment]
在head部分的head.ejs文件加入了三行代码
<meta name="referrer"content="origin">
<meta name="referrer" content="no-referrer">
<meta name="referrer" content="no-referrer" />
同时关闭了github的强制https，保留了ssl证书
发现显示出来前面几张图片，博客地址 capdream.cn
目前不知道那里的问题，搭建使用的ubuntu+github+hexo+语雀同步

**Comment by capdream** [comment]
> > 请问有最新版的吗？加上head也无法显示
> 
> 可以开启工具 CDN 转存的功能

请问这个在哪，还是说的图床？
