### ISSUE TITLE
1.6.2版本依然会重复front-matter

### ISSUE THREAD

**Issue by TomatoFryEggs** [x-cold/yuque-hexo#45]
![image](https://user-images.githubusercontent.com/9395814/69145669-231dfb00-0b09-11ea-8a37-d508526a55df.png)

**Comment by x-cold** [comment]
原文发一下？

**Comment by TomatoFryEggs** [comment]
> 原文发一下？

https://www.yuque.com/che1994/blog/nsge0s

**Comment by x-cold** [comment]
@k-water 看看？

**Comment by TomatoFryEggs** [comment]
就**经验**找到一个**可能**的原因：
因为是markdown导入的，---和正文开头连一起，在---下加入空行时，语雀默认将---后的空行设置成标题样式。

**Comment by TomatoFryEggs** [comment]
不知道怎么就好了。
不会重复了。

PS: tags需要加 [ ] ，即使只有一个，否则会不生效。

**Comment by x-cold** [comment]
可能是 hexo-front-matter 的识别规则，必须要求是符合匹配规则的 meta 才能识别，否则就会出现上面这种情况，会有两层的 meta。1 层是 yuque-hexo 会加上的，另一层是原文中没有被识别成 meta 的（正常来说会被识别并且移除掉）。https://github.com/x-cold/yuque-hexo/blob/master/adapter/hexo.js#L33
