### ISSUE TITLE
1.6.2版本的front-matter 好像还是有问题.

### ISSUE THREAD

**Issue by HPShark** [x-cold/yuque-hexo#48]
![image](https://user-images.githubusercontent.com/24475140/71476785-ca393500-2821-11ea-94ad-3cad5f0c12de.png)

文章地址：https://www.yuque.com/hpshark/blog/czkv6n
请问这个是我设置错了吗？谢谢

**Comment by HPShark** [comment]
![image](https://user-images.githubusercontent.com/24475140/71477064-f7d2ae00-2822-11ea-8e97-007db69ef919.png)
分割线不转换还是这个样子....

**Comment by x-cold** [comment]
换行有问题

**Comment by lengthmin** [comment]
ejs 编译的问题
node_modules 里手动修改成这样才行
```ejs
const template = `---<% for (const key in props) { %>
<%= key %>: <%= props[key] -%>
<% } %>
---
<%- raw -%>
`;
```
文件位置：https://github.com/x-cold/yuque-hexo/blob/master/adapter/hexo.js#L11

**Comment by HPShark** [comment]
谢谢大佬们，我去试试！
