### ISSUE TITLE
用户自定义 adapter

### ISSUE THREAD

**Issue by lengthmin** [x-cold/yuque-hexo#49]
不同的主题需要不同的 front_matter
比如我自己就需要 permalink updated 这些字段
然后我就得改源代码

如果有一个方案可以传入自定义的 adapter 就可以了，把  config 写在一个 js 文件中

如果 typeof config.adapter=="string"
== "function" 的话就传入数据

类似的

可以讨论一下

**Comment by x-cold** [comment]
可以的 欢迎 MR

**Comment by x-cold** [comment]
这个 adapter 当初也是为了让大家如果有自定义需求，可以无缝进行开放

**Comment by SylleoYr** [comment]
yuque-hexo 对自定义的 frontmatter 读取还是有点问题 😭，要不生成不对要不就是没有 tag 和 category。

还是再配置里把 adpater 改成 markdown 好用，缺点就是要自己在文章中添加完整的 frontmatter，需要手动填写 date 和 updated，但是这样对自定义的 frontmatter 最友好。可以在设置一个模板，基本上可以说 perfect 了 😂

> tips：注意语雀中 frontmatter 冒号后面的空格，一定要有空格（yml语法），不然 Hexo 会解析失败，这个问题搞了我一上午 😱

**Comment by x-cold** [comment]
1.8.0 可以支持自己定义 adapter 脚本了，具体可以参考这个实例：https://github.com/x-cold/yuque-hexo/tree/master/test/custom-adapter-project
