### ISSUE TITLE
语雀里的分类不同步过来的？

### ISSUE THREAD

**Issue by nic519** [x-cold/yuque-hexo#50]

**Comment by x-cold** [comment]
语雀里面应该没有分类的概念吧？目前只能通过 meta 的方式来定义分类（categories）

**Comment by wztlink1013** [comment]
@x-cold 应该指的是知识库的目录，就是文章分组，看起来像是文章分类。

我看语雀开发者文档中，有相应目录的api，这个应该能实现吧。
