### ISSUE TITLE
语雀文档同步失败

### ISSUE THREAD

**Issue by francis-du** [x-cold/yuque-hexo#51]
之前一直正常的，最近这几天不知道为啥没法同步文档了，怎么肥四？？？

 Error: fail to fetch article list, response: {"status":401,"message":"Unauthorized"}

![image](https://user-images.githubusercontent.com/25944814/74503818-20c31580-4f2d-11ea-94fe-1b290843fc85.png)

**Comment by francis-du** [comment]
语雀文档是公开的~

**Comment by YUUtan1994** [comment]
same question here.编译了很多次，把yuque-hexo更新到1.6.2版本，还是返回401，可能语雀那边做了什么限制。之前是正常的

**Comment by x-cold** [comment]
需要设置一下你的 TOKEN，如果拉数据频率很高的话，会被服务器限流的。

**Comment by francis-du** [comment]
每天拉一次~

**Comment by x-cold** [comment]
每一篇文章的拉取，都需要调用一次 API 哦

• 匿名请求，IP 限制, 200 次/小时
• 传递 Token 的情况下，每个用户（基于 Token 关联到的账户），5000 次/小时；

失效会返回 429 返回码。

https://www.yuque.com/yuque/developer/api#5b3a1535

楼上有一个是 401 返回码的，应该是仓库权限的问题，传入 TOKEN 也能解决

**Comment by iszengmh** [comment]
token怎么设置，我看readme.md中写注入环境变量怎么注入，我在电脑上创建了环境变量，但是没有用，如果是travis-ci上怎么设置的

**Comment by francis-du** [comment]
同问

**Comment by x-cold** [comment]
travis ci 注入 token
![image](https://user-images.githubusercontent.com/6903313/75644958-2afc4800-5c7f-11ea-9848-bbd515215c63.png)

**Comment by x-cold** [comment]
电脑本地的环境变量就按照常规的方式设置即可。
linux / osx: https://blog.csdn.net/yi412/article/details/11523525
windows: https://blog.csdn.net/palmer_kai/article/details/80588594

或者通过执行命令时带参数
linux / mac: YUQUE_TOKEN=xxx yuque-hexo sync
window: set YUQUE_TOKEN && yuque-hexo sync

**Comment by francis-du** [comment]
@x-cold 好了，搞定，谢谢~
