### ISSUE TITLE
请教一个小问题，关于token正常情况下，拉取数据之后无法创建文章md的问题

### ISSUE THREAD

**Issue by lweein** [x-cold/yuque-hexo#52]
截图里面一个是json配置文件，一个是配置文件，一个是代码报错，想请问会是哪方面的原因呢？

![QQ浏览器截图20200221214543](https://user-images.githubusercontent.com/13096524/75039513-cfe68a80-54f3-11ea-859f-3d949e41479b.jpg)

![QQ浏览器截图20200221214533](https://user-images.githubusercontent.com/13096524/75039489-c6f5b900-54f3-11ea-9e5b-7b362d13c878.jpg)

**Comment by lweein** [comment]
不是使用DEBUG。。。。

**Comment by x-cold** [comment]
看起来好像是文件名的问题，你可以加我 wechat 看下
yangpengfei19951026

**Comment by x-cold** [comment]
这个已经解决了，title 中的斜杠在 windows 系统下不能支持
