### ISSUE TITLE
能不能排除模板文章？

### ISSUE THREAD

**Issue by zuixiaoyao0875** [x-cold/yuque-hexo#53]

**Comment by zuixiaoyao0875** [comment]
![](https://cdn.jsdelivr.net/gh/zuixiaoyao0875/tuchuang@master/20200228182015.png)

**Comment by x-cold** [comment]
这个可以有 我抽空解决一下

**Comment by x-cold** [comment]
官方的 API 中目前暂时无法分辨 Doc 是否模板的属性，待跟进 https://www.yuque.com/yuque/developer/docserializer

**Comment by buyucoder** [comment]
可以考虑将模板的slug设置为特殊的格式,如 `___ingore_tpl___` ,再从代码中过滤

**Comment by x-cold** [comment]
也不是不行~ 不过我感觉语雀官方支持会更合适一些，我们去万人血书让他们支持下吧 哈哈哈

**Comment by x-cold** [comment]
设为私密吧 现在已经支持过滤私密了

**Comment by andjiawei** [comment]
模板文件我已经删了，也从回收站清楚了，同步后 依然会到本地，有点尴尬
