### ISSUE TITLE
服务器开小差了，请稍后再试，反馈码：0a51437a1583161675465704117522

### ISSUE THREAD

**Issue by hongweifuture** [x-cold/yuque-hexo#54]
今天同步出现了这个错误
⚠️  Error: 服务器开小差了，请稍后再试（反馈码：0a51437a1583161675465704117522）
⚠️  Command Error, enable `DEBUG=common-bin` for detail

**Comment by hongweifuture** [comment]
[INFO] remove yuque posts: /home/runner/work/blog-hexo-halo/blog-hexo-halo/source/_posts
[INFO] remove yuque local cache: /home/runner/work/blog-hexo-halo/blog-hexo-halo/yuque.json
[WARNING] ENOENT: no such file or directory, unlink '/home/runner/work/blog-hexo-halo/blog-hexo-halo/yuque.json'
[INFO] yuque-hexo clean done!
[INFO] clear previous directory.
[INFO] remove yuque posts: /home/runner/work/blog-hexo-halo/blog-hexo-halo/source/_posts
[INFO] reading from local file: /home/runner/work/blog-hexo-halo/blog-hexo-halo/yuque.json
[INFO] article amount: 12
[INFO] download article body: 配合Valine评论系统使用的Valine-Admin及显示个性头像
[INFO] download article body: Github Actions--通过 SSH 自动备份代码到托管网站
[INFO] download article body: Github Actions--通过 SSH 自动部署 Hexo
[INFO] download article body: Github Actions--云打包创建 docker 镜像
[INFO] download article body: 无标题
[INFO] download article body: Github Actions--通过 API 自动部署 Hexo
[INFO] download article body: MySQL 教程--增删改查
⚠️  Error: 服务器开小差了，请稍后再试（反馈码：0a51437a1583161675465704117522）
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-site@0.0.0 start: `yuque-hexo clean && yuque-hexo sync && hexo clean && hexo generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hexo-site@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-03-02T15_07_55_986Z-debug.log
##[error]Process completed with exit code 1.

**Comment by hongweifuture** [comment]
通过更换知识库解决了这个问题，但是依然不知道这个问题出在哪里

**Comment by tingkai-zhang** [comment]
同样遇到这个问题了。
你说的更换知识库是什么意思？

**Comment by zephyr-y** [comment]
我也遇到了同样的问题，是不是语雀api调整了啥？

**Comment by hongweifuture** [comment]
> 同样遇到这个问题了。
> 你说的更换知识库是什么意思

我是把语雀端重新弄了一下：
1. 新建知识库，将原来知识库文章移动或者复制过来
2. 修改package.json更新地址
3. 添加web hook

**Comment by hongweifuture** [comment]
> 我也遇到了同样的问题，是不是语雀api调整了啥？

我是把语雀端重新弄了一下：
1. 新建知识库，将原来知识库文章移动或者复制过来
2. 修改package.json更新地址
3. 添加web hook

**Comment by hongweifuture** [comment]
安利一个Hexo使用yuque-hexo的最新方式，语雀云端写作 Github Actions 持续集成
https://www.zhwei.cn/hexo-github-actions-yuque/
https://blog.csdn.net/z_johnny/article/details/104629805
thanks~

**Comment by x-cold** [comment]
已放到文档最佳实践

**Comment by x-cold** [comment]
还有错误的同学可以试试配置 YUQUE_TOKEN

**Comment by hongweifuture** [comment]
> �已放到文档最佳实践

谢谢，希望可以帮助到大家。
