### ISSUE TITLE
知识库是共有的，在更新时提示Unauthorized

### ISSUE THREAD

**Issue by HKMV** [x-cold/yuque-hexo#55]
我的知识库是公有的，今天在更新的时候不知道为何提示需要认真
`⚠️  Error: fail to fetch article list, response: {"status":401,"message":"Unauthorized"}
⚠️  Command Error, enable `DEBUG=common-bin` for detail`

![image](https://user-images.githubusercontent.com/26456469/75850955-75b6c500-5e23-11ea-91ae-f92a79a30e66.png)

**Comment by HKMV** [comment]
已解决：设置环境变量 `set YUQUE_TOKEN=xxx`即可。
但是公共的库不应该需要呀，不太明白为什么也需要。

**Comment by x-cold** [comment]
这应该是语雀的安全策略调整了，避免公共数据被匿名爬取哦

**Comment by HKMV** [comment]
> 这应该是语雀的安全策略调整了，避免公共数据被匿名爬取哦

哦哦，谢谢您。

**Comment by wztlink1013** [comment]
@HKMV 你好，我遇到和你一样的问题，建立后还是没用，请问是在博客根文件夹下键入这条命令吗？

**Comment by HKMV** [comment]
> @HKMV 你好，我遇到和你一样的问题，建立后还是没用，请问是在博客根文件夹下键入这条命令吗？

是的，就是设置一个临时的环境变量，更新操作的时候会用到。

**Comment by wztlink1013** [comment]
@HKMV ![](https://wztlink1013.coding.net/p/figure/d/figure/git/raw/master/Snipaste_2020-06-01_12-38-11.png)

好像还是有问题，请问需要其他操作吗

**Comment by HKMV** [comment]
> @HKMV ![](https://camo.githubusercontent.com/6377b07ada15d8b028e65f844cb79f02f0a14d77/68747470733a2f2f777a746c696e6b313031332e636f64696e672e6e65742f702f6669677572652f642f6669677572652f6769742f7261772f6d61737465722f536e6970617374655f323032302d30362d30315f31322d33382d31312e706e67)
> 
> 好像还是有问题，请问需要其他操作吗

那就不晓滴了，等官方人员回复吧

**Comment by wztlink1013** [comment]
@HKMV 已解决，放在系统环境变量就可以了
