### ISSUE TITLE
categories同步后[]丢失

### ISSUE THREAD

**Issue by khalidzk** [x-cold/yuque-hexo#56]
categories同步后[]丢失
1、二级目录写法
语雀中写法：
`
categories: [Java,Jvm]
`
同步之后：
`
categories: Java,Jvm
`
2、双目录写法
语雀中写法：

categories: 
  - [Java,Jvm]
  - [study]

同步之后：

`
categories: Java,Jvm,study
`
hexo本身是支持这种写法的，见https://hexo.io/zh-cn/docs/front-matter
请问一下这是在语雀中的写法问题吗

**Comment by x-cold** [comment]
应该是 ejs 渲染的时候没有兼容二维数组的序列化。
[
[Java,Jvm],
[study]
]
被序列化成
Java,Jvm,study

**Comment by x-cold** [comment]
v1.6.3 

#6c722b5c5c1c2a47f6275027ab93db02fde3e5e9

**Comment by khalidzk** [comment]
thank you
