### ISSUE TITLE
关于图片无法访问的问题

### ISSUE THREAD

**Issue by HKMV** [x-cold/yuque-hexo#57]
我在语雀发表的文章中包含图片，同步到hexo后访问图片好像不具有权限，导致文章中的图片无法加载，请问怎么解决呢。
![image](https://user-images.githubusercontent.com/26456469/76476987-e02cbe00-643e-11ea-8c8c-3ae700c37942.png)

直接打开图片提示403错误，判断应该是访问被禁止。
![image](https://user-images.githubusercontent.com/26456469/76477044-15391080-643f-11ea-9291-a4ef730a3080.png)

**Comment by x-cold** [comment]
41

**Comment by x-cold** [comment]
#41 41

**Comment by HKMV** [comment]
> #41 41

感谢大佬
