### ISSUE TITLE
语雀同步到hexo文档问题

### ISSUE THREAD

**Issue by Leader755** [x-cold/yuque-hexo#62]
代码块被自动分成左右2块，求解决办法，或者其他更好的语雀一键同步到hexo。
![image](https://user-images.githubusercontent.com/37180494/81035411-66a8cd80-8ecd-11ea-8a95-f3d02aa48f2c.png)

**Comment by x-cold** [comment]
具体分析下正常 、异常的 Markdown 片段？

**Comment by x-cold** [comment]
由于没有补充具体信息，无法继续排查，这个 issue 我先关闭啦
