### ISSUE TITLE
插件生成文章失败 或者 请求经常超时

### ISSUE THREAD

**Issue by Hosiang1026** [x-cold/yuque-hexo#63]
![image](https://user-images.githubusercontent.com/28383042/82148130-11819a00-9885-11ea-92bc-ffbe580e71a3.png)

插件生成文章失败 或者 请求经常超时， 之前是正常的同步，也不知道是不是语雀的版本升级导致的。md文件默认增加了很多换行br

**Comment by x-cold** [comment]
我晚点看看

**Comment by x-cold** [comment]
最新版已修复
