### ISSUE TITLE
yueque-hexo sync时报错：TypeError: Lu(...).content.trimStart is not a function

### ISSUE THREAD

**Issue by luckyTiamo** [x-cold/yuque-hexo#66]
这个问题没看到其他人遇到
![image](https://user-images.githubusercontent.com/48179927/86221005-ec3bb780-bbb6-11ea-9938-d0a9aa4c4997.png)

**Comment by x-cold** [comment]
可以试试 debug 模式，看下具体是卡在哪个点上，看上去像是你的文章内容为空之类的原因导致的
