### ISSUE TITLE
关于转换文档时图片的问题

### ISSUE THREAD

**Issue by lfsds** [x-cold/yuque-hexo#69]
能否实现转换文档时对图片进行配置，支持将图片下载到本地同名文件夹下。（担心因为防盗链图片彻底不能使用的问题，临时方案也无效的情况下）

**Comment by x-cold** [comment]
目前还没支持的计划，同步过来会导致访问比较慢，语雀短期内也不会加强这部分的策略。

**Comment by x-cold** [comment]
有兴趣支持的话 可以在 adapter 层做相关的扩展

**Comment by hacker-jerry** [comment]
> 目前还没支持的计划，同步过来会导致访问比较慢，语雀短期内也不会加强这部分的策略。

emm我觉得是不是在github action中将图片下载到img文件夹，然后使用jsdriver的cdn加速，在md转换层 将图片外链引用改成类似于https://cdn.jsdelivr.net/gh/AlanDecode/site-Blog@gh-pages/img/13452d991bfec0ed426cd0615bc53703.png的样式？

具体灵感来自于https://sspai.com/post/58013

**Comment by hacker-jerry** [comment]
> 能否实现转换文档时对图片进行配置，支持将图片下载到本地同名文件夹下。（担心因为防盗链图片彻底不能使用的问题，临时方案也无效的情况下）

哈哈，自己动手丰衣足食。js代码我不太会写，就用python写了一个脚本，批量转换语雀外链到又拍云。不知道能不能集成到yuque-hexo里

**Comment by x-cold** [comment]
1.8.0 已经支持自定的 adapter 代码了，可以参考这个 https://github.com/x-cold/yuque-hexo/tree/master/test/custom-adapter-project，可以考虑在 adapter 实现相关的代码。

当然如果你的图片转存的逻辑已经用 python 实现了，那直接在 yuque-hexo sync 命令之后加上你的命令就好啦，比如 yuque-hexo sync && ptython ./my_python.py。
