### ISSUE TITLE
图片大小问题

### ISSUE THREAD

**Issue by wakaka123wakaka** [x-cold/yuque-hexo#70]
语雀同步到github图片大小无法自动调整，看着不怎么协调，请问有什么办法呢

**Comment by x-cold** [comment]
语雀上面调整后同步过来，语雀的方案是在 url 加上 width height 参数，我觉得够用

**Comment by wakaka123wakaka** [comment]
有没有什么脚本可以实现了 ，如果一张一张的加进去就不是那么方便了

尹挚 <notifications@github.com> 于2020年8月16日周日 下午4:32写道：
