### ISSUE TITLE
语雀中添加tags等标签无法转换

### ISSUE THREAD

**Issue by hacker-jerry** [x-cold/yuque-hexo#71]
您好，我按照你的方法做，分了一个私有仓库，一个共有仓库。私有存放hexo源码，公有存放生成的page文件，也部署成功了，但是源码的仓库中没有导入语雀的文章，即source/post中没有文章，也没有产生yuque.json文件，但是我在看github action的具体操作中，是存在例如 create xxx/xxx/source/post/yuque_post1.md 类似这样的信息，也就是说它确实下载下来了，但是我并没有找到它（在私有仓库的source文件夹中）。

之所以想找到它，是因为我使用front-matter写文章头的时候，希望添加tags,top_img类似的信息，但是转换成网页之后它们在原文中当作文本信息输出了，而不是相关的标签或分类。
这是语雀中的↓按照yuque-hexo的readme
![](https://image.hackerjerry.top/uTools_1598413862425.png)
然后在实际博客中
![](https://image.hackerjerry.top/uTools_1598414014067.png)
请问如何解决的？谢谢！

**Comment by x-cold** [comment]
原文贴个链接呗

**Comment by hacker-jerry** [comment]
啊我又修改了一下，发现是因为top_img这个front-matter名无法转换，去掉他就可以了。请问不可以自定义md的头吗？就是
---
---
之间的内容？

**Comment by hacker-jerry** [comment]
> 原文贴个链接呗

啊我又修改了一下，发现是因为top_img这个front-matter名无法转换，去掉他就可以了。请问不可以自定义md的头吗？就是
---
xxx:
xxx:
---
之间的内容？

**Comment by x-cold** [comment]
去掉下划线试试？是可以自定义的

**Comment by hacker-jerry** [comment]
好的好的谢谢啦

> 去掉下划线试试？是可以自定义的
