### ISSUE TITLE
cover问题

### ISSUE THREAD

**Issue by ciweigg2** [x-cold/yuque-hexo#73]
版本1.6.0
语雀格式：
tags: [SpringBoot]
categories: [SpringBoot]
cover: https://cdn.nlark.com/yuque/0/2019/jpeg/155457/1546857679810-d82e3d46-e960-419c-a715-0a82c48a2fd6.jpeg#align=left&display=inline&height=225&name=image.jpeg&originHeight=225&originWidth=225&size=6267&width=225
---
效果：
tags: [SpringBoot]
categories: [SpringBoot]
cover: [https://cdn.nlark.com/yuque/0/2019/jpeg/155457/1546857679810-d82e3d46-e960-419c-a715-0a82c48a2fd6.jpeg#align=left&display=inline&height=225&name=image.jpeg&originHeight=225&originWidth=225&size=6267&width=225](https://cdn.nlark.com/yuque/0/2019/jpeg/155457/1546857679810-d82e3d46-e960-419c-a715-0a82c48a2fd6.jpeg#align=left&display=inline&height=225&name=image.jpeg&originHeight=225&originWidth=225&size=6267&width=225)

**Comment by hfsyun** [comment]
你在语雀写文章的时候去掉a链接，比如这样
![O8oqt2IhHkKGfyr.png](https://i.loli.net/2020/10/08/O8oqt2IhHkKGfyr.png)
