### ISSUE TITLE
中英文混写会在英文的两边出现空格。

### ISSUE THREAD

**Issue by lmikoto** [x-cold/yuque-hexo#74]
比如语雀上是 
> 你好hexo博客。

下载下来的文章变成了

> 你好 hexo 博客

**Comment by mohuishou** [comment]
这个应该是自动格式化了，直接下载 markdown 文件格式比较混乱，所以引入了格式化的库

**Comment by x-cold** [comment]
https://prettier.io/blog/2017/11/07/1.8.0.html

**Comment by x-cold** [comment]
这个排版问题我理解是可以接受格式化的，看下对你实际影响有多大呢？@Imikoto
