### ISSUE TITLE
sync请求超时导致action中断问题

### ISSUE THREAD

**Issue by Zfour** [x-cold/yuque-hexo#77]
`ConnectionTimeoutError: Connect timeout for 5000ms, GET https://www.yuque.com/api/v2/repos/bingkanuo/sffipz/docs/vi48ze -2 (connected: false, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 0)`

**Comment by mohuishou** [comment]
有时候会有这个问题，你可以试试配置一下重试，一般重试个两次就可以了

**Comment by x-cold** [comment]
超时问题如果是低频次出现建议尝试，也可以在 CICD 中进行尝试哈
