### ISSUE TITLE
在 sync的时候经常出现超时的问题(频次高), 有时候又是正常的.

### ISSUE THREAD

**Issue by Mvbbb** [x-cold/yuque-hexo#80]
![image](https://user-images.githubusercontent.com/56795364/103783065-35dbf200-5073-11eb-8ffc-096832f5d5f0.png)
![image](https://user-images.githubusercontent.com/56795364/103783455-b6025780-5073-11eb-83e4-1237a53ba8a2.png)
版本是: v1.7.0
已配置Token

**Comment by x-cold** [comment]
试试把 concurrency 调小一些，比如调成 2-3 应该会减少一些超时的情况

**Comment by Zfour** [comment]
海外访问api下载时间超过5s了吧，建议看看有没有办法能够修改超时时间长一点。

**Comment by Leader755** [comment]
对，我也有这情况，GitHub的action中调用yuque-hexo sync，有时候会失败，有时候又会成功。不知道咋回事，主要都说超时。
![Uploading 12E2F26F-2595-4714-868B-EA5F9BE8AB5E.png…]()

**Comment by Leader755** [comment]
好像是我代码问题，但是读取yuque.json文件失败。

**Comment by Leader755** [comment]
好像是我代码问题，但是读取yuque.json文件失败。

> 
![Uploading E5BCBCF8-2F01-400D-9375-35017268DD71.png…]()

**Comment by Leader755** [comment]
> ![image](https://user-images.githubusercontent.com/56795364/103783065-35dbf200-5073-11eb-8ffc-096832f5d5f0.png)
> ![image](https://user-images.githubusercontent.com/56795364/103783455-b6025780-5073-11eb-83e4-1237a53ba8a2.png)
> 版本是: v1.7.0
> 已配置Token

你这是在coding构建的吗

**Comment by Mvbbb** [comment]
> 海外访问api下载时间超过5s了吧，建议看看有没有办法能够修改超时时间长一点。

我之前是在Coding构建的,coding使用的是国内的节点, 出现了这种问题, 之后迁移到GitHub action也出现了这种问题

**Comment by Mvbbb** [comment]
> > ![image](https://user-images.githubusercontent.com/56795364/103783065-35dbf200-5073-11eb-8ffc-096832f5d5f0.png)
> > ![image](https://user-images.githubusercontent.com/56795364/103783455-b6025780-5073-11eb-83e4-1237a53ba8a2.png)
> > 版本是: v1.7.0
> > 已配置Token
> 
> 你这是在coding构建的吗

coding和GitHub都出现了这种问题

**Comment by Leader755** [comment]
应该可以将超时时间设置长一点。其实啊，有个问题，文章一多同步的时间是不是一定会很长呢，抛开网速。克隆github的代码的超时是怎么设置的。

**Comment by Zfour** [comment]
今天早上基本全部阵亡了

**Comment by Leader755** [comment]
能不能报超时时间提出来自定义，或者默认设置更长的时间

**Comment by Zfour** [comment]
我研究出来了，貌似这个下载超时可以用设置timeout实现

```
 "yuqueConfig": {
    "postPath": "source/_posts",
    "cachePath": "yuque.json",
    "mdNameFormat": "title",
    "adapter": "markdown",
    "concurrency": 1,
    "baseUrl": "https://yuque.com/api/v2",
    "login": "bingkanuo",
    "repo": "sffipz",
    "token": "xxxxxxxx",
    "timeout": "none",
    "onlyPublished": true,
    "onlyPublic": true
  },
```

大家可以试试看，我这里设置的是没有timeout，应该也可以设置数字秒。

**Comment by Leader755** [comment]
> 我研究出来了，貌似这个下载超时可以用设置timeout实现
> 
> ```
>  "yuqueConfig": {
>     "postPath": "source/_posts",
>     "cachePath": "yuque.json",
>     "mdNameFormat": "title",
>     "adapter": "markdown",
>     "concurrency": 1,
>     "baseUrl": "https://yuque.com/api/v2",
>     "login": "bingkanuo",
>     "repo": "sffipz",
>     "token": "xxxxxxxx",
>     "timeout": "none",
>     "onlyPublished": true,
>     "onlyPublic": true
>   },
> ```
> 
> 大家可以试试看，我这里设置的是没有timeout，应该也可以设置数字秒。

试过没

**Comment by Zfour** [comment]
> > 我研究出来了，貌似这个下载超时可以用设置timeout实现
> > ```
> >  "yuqueConfig": {
> >     "postPath": "source/_posts",
> >     "cachePath": "yuque.json",
> >     "mdNameFormat": "title",
> >     "adapter": "markdown",
> >     "concurrency": 1,
> >     "baseUrl": "https://yuque.com/api/v2",
> >     "login": "bingkanuo",
> >     "repo": "sffipz",
> >     "token": "xxxxxxxx",
> >     "timeout": "none",
> >     "onlyPublished": true,
> >     "onlyPublic": true
> >   },
> > ```
> > 
> > 
> > 大家可以试试看，我这里设置的是没有timeout，应该也可以设置数字秒。
> 
> 试过没

我试过了一次，貌似没问题

**Comment by Zfour** [comment]
> > 我研究出来了，貌似这个下载超时可以用设置timeout实现
> > ```
> >  "yuqueConfig": {
> >     "postPath": "source/_posts",
> >     "cachePath": "yuque.json",
> >     "mdNameFormat": "title",
> >     "adapter": "markdown",
> >     "concurrency": 1,
> >     "baseUrl": "https://yuque.com/api/v2",
> >     "login": "bingkanuo",
> >     "repo": "sffipz",
> >     "token": "xxxxxxxx",
> >     "timeout": "none",
> >     "onlyPublished": true,
> >     "onlyPublic": true
> >   },
> > ```
> > 
> > 
> > 大家可以试试看，我这里设置的是没有timeout，应该也可以设置数字秒。
> 
> 试过没

貌似又不行了，还是会有5000ms那个报错...

**Comment by Leader755** [comment]
> > > 我研究出来了，貌似这个下载超时可以用设置timeout实现
> > > ```
> > >  "yuqueConfig": {
> > >     "postPath": "source/_posts",
> > >     "cachePath": "yuque.json",
> > >     "mdNameFormat": "title",
> > >     "adapter": "markdown",
> > >     "concurrency": 1,
> > >     "baseUrl": "https://yuque.com/api/v2",
> > >     "login": "bingkanuo",
> > >     "repo": "sffipz",
> > >     "token": "xxxxxxxx",
> > >     "timeout": "none",
> > >     "onlyPublished": true,
> > >     "onlyPublic": true
> > >   },
> > > ```
> > > 
> > > 
> > > 大家可以试试看，我这里设置的是没有timeout，应该也可以设置数字秒。
> > 
> > 
> > 试过没
> 
> 貌似又不行了，还是会有5000ms那个报错...

我刚刚咋成功了，我咋没看到这个timeout属性嗯。

**Comment by Zfour** [comment]
> > > > 我研究出来了，貌似这个下载超时可以用设置timeout实现
> > > > ```
> > > >  "yuqueConfig": {
> > > >     "postPath": "source/_posts",
> > > >     "cachePath": "yuque.json",
> > > >     "mdNameFormat": "title",
> > > >     "adapter": "markdown",
> > > >     "concurrency": 1,
> > > >     "baseUrl": "https://yuque.com/api/v2",
> > > >     "login": "bingkanuo",
> > > >     "repo": "sffipz",
> > > >     "token": "xxxxxxxx",
> > > >     "timeout": "none",
> > > >     "onlyPublished": true,
> > > >     "onlyPublic": true
> > > >   },
> > > > ```
> > > > 
> > > > 
> > > > 大家可以试试看，我这里设置的是没有timeout，应该也可以设置数字秒。
> > > 
> > > 
> > > 试过没
> > 
> > 
> > 貌似又不行了，还是会有5000ms那个报错...
> 
> 我刚刚咋成功了，我咋没看到这个timeout属性嗯。

刚才估计是碰巧成功了...现在又不行了

**Comment by Leader755** [comment]
> > > > > 我研究出来了，貌似这个下载超时可以用设置timeout实现
> > > > > ```
> > > > >  "yuqueConfig": {
> > > > >     "postPath": "source/_posts",
> > > > >     "cachePath": "yuque.json",
> > > > >     "mdNameFormat": "title",
> > > > >     "adapter": "markdown",
> > > > >     "concurrency": 1,
> > > > >     "baseUrl": "https://yuque.com/api/v2",
> > > > >     "login": "bingkanuo",
> > > > >     "repo": "sffipz",
> > > > >     "token": "xxxxxxxx",
> > > > >     "timeout": "none",
> > > > >     "onlyPublished": true,
> > > > >     "onlyPublic": true
> > > > >   },
> > > > > ```
> > > > > 
> > > > > 
> > > > > 大家可以试试看，我这里设置的是没有timeout，应该也可以设置数字秒。
> > > > 
> > > > 
> > > > 试过没
> > > 
> > > 
> > > 貌似又不行了，还是会有5000ms那个报错...
> > 
> > 
> > 我刚刚咋成功了，我咋没看到这个timeout属性嗯。
> 
> 刚才估计是碰巧成功了...现在又不行了
没看到这个timeout属性啊

![image](https://user-images.githubusercontent.com/37180494/104275811-8bcef080-54de-11eb-81d5-c0ba3754312f.png)

**Comment by Zfour** [comment]
> > > > > > 我研究出来了，貌似这个下载超时可以用设置timeout实现
> > > > > > ```
> > > > > >  "yuqueConfig": {
> > > > > >     "postPath": "source/_posts",
> > > > > >     "cachePath": "yuque.json",
> > > > > >     "mdNameFormat": "title",
> > > > > >     "adapter": "markdown",
> > > > > >     "concurrency": 1,
> > > > > >     "baseUrl": "https://yuque.com/api/v2",
> > > > > >     "login": "bingkanuo",
> > > > > >     "repo": "sffipz",
> > > > > >     "token": "xxxxxxxx",
> > > > > >     "timeout": "none",
> > > > > >     "onlyPublished": true,
> > > > > >     "onlyPublic": true
> > > > > >   },
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 大家可以试试看，我这里设置的是没有timeout，应该也可以设置数字秒。
> > > > > 
> > > > > 
> > > > > 试过没
> > > > 
> > > > 
> > > > 貌似又不行了，还是会有5000ms那个报错...
> > > 
> > > 
> > > 我刚刚咋成功了，我咋没看到这个timeout属性嗯。
> > 
> > 
> > 刚才估计是碰巧成功了...现在又不行了
> > 没看到这个timeout属性啊
> 
> ![image](https://user-images.githubusercontent.com/37180494/104275811-8bcef080-54de-11eb-81d5-c0ba3754312f.png)

我以为这里可以传网络请求的“timeout”属性，所以加的timeout，结果刚刚试了貌似没用，还是5000ms

**Comment by Leader755** [comment]
> > > > > > > 我研究出来了，貌似这个下载超时可以用设置timeout实现
> > > > > > > ```
> > > > > > >  "yuqueConfig": {
> > > > > > >     "postPath": "source/_posts",
> > > > > > >     "cachePath": "yuque.json",
> > > > > > >     "mdNameFormat": "title",
> > > > > > >     "adapter": "markdown",
> > > > > > >     "concurrency": 1,
> > > > > > >     "baseUrl": "https://yuque.com/api/v2",
> > > > > > >     "login": "bingkanuo",
> > > > > > >     "repo": "sffipz",
> > > > > > >     "token": "xxxxxxxx",
> > > > > > >     "timeout": "none",
> > > > > > >     "onlyPublished": true,
> > > > > > >     "onlyPublic": true
> > > > > > >   },
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > 大家可以试试看，我这里设置的是没有timeout，应该也可以设置数字秒。
> > > > > > 
> > > > > > 
> > > > > > 试过没
> > > > > 
> > > > > 
> > > > > 貌似又不行了，还是会有5000ms那个报错...
> > > > 
> > > > 
> > > > 我刚刚咋成功了，我咋没看到这个timeout属性嗯。
> > > 
> > > 
> > > 刚才估计是碰巧成功了...现在又不行了
> > > 没看到这个timeout属性啊
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/37180494/104275811-8bcef080-54de-11eb-81d5-c0ba3754312f.png)
> 
> 我以为这里可以传网络请求的“timeout”属性，所以加的timeout，结果刚刚试了貌似没用，还是5000ms

我说呢，我建议作者是不是可以把超时时间默认设置长一点，或者放出来自定义。还有个问题语雀服务是不是也会有限制时间呢。

**Comment by Leader755** [comment]
哎，最近老失败

**Comment by x-cold** [comment]
目前这部分应该是在 yuque sdk 层面的超时，可以 MR 来试试

https://github.com/yuque/sdk/blob/master/lib/client.js#L28

主要需要在这里透传一下 requestOpts 参数：https://github.com/x-cold/yuque-hexo/blob/master/lib/yuque.js#L26

**Comment by Zfour** [comment]
所以大概怎么改呢(  ･᷄ὢ･᷅  )嗯？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;尹挚&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月18日(星期一) 中午11:44
收件人:&nbsp;&quot;x-cold/yuque-hexo&quot;<yuque-hexo@noreply.github.com&gt;;
抄送:&nbsp;&quot;Zfour&quot;<499984532@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [x-cold/yuque-hexo] 在 sync的时候经常出现超时的问题(频次高), 有时候又是正常的. (#80)

**Comment by Leader755** [comment]
那如果执行失败重试呢

**Comment by Zfour** [comment]
```
    - name: 更新 语雀拉取缓存及文章 #更新yuque 拉取的文章到GitHub仓库
      run: |
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        git config --global user.email "youname@email.com"
        git config --global user.name "youname"
        git add .
        git commit -m "Refresh yuque json" -a

    - name: 推送 语雀拉取缓存及文章  #推送修改后的yuque json
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

通过向博客源代码库推送yuque.json，减少每次拉取的文章数。
这样可以在每次action时，尽量从服务器下载最少数量的文章。

**Comment by MCSeekeri** [comment]
我这也有同样的问题,将concurrency改为1都不行（叹气
在源代码库里保存语雀文章治标不治本...假如我在语雀新建了一篇很长的文章呢...
如果是语雀那边的问题的话...目前我能想到的解决方案就是支持自定义timeout...或者加入失败重试机制
@x-cold 希望前辈能够修复这个问题（鞠躬

**Comment by lonbaw** [comment]
> 我这也有同样的问题,将concurrency改为1都不行（叹气
> 在源代码库里保存语雀文章治标不治本...假如我在语雀新建了一篇很长的文章呢...
> 如果是语雀那边的问题的话...目前我能想到的解决方案就是支持自定义timeout...或者加入失败重试机制
> @x-cold 希望前辈能够修复这个问题（鞠躬
作者给了解决方案，可以参考这个，提交PR修复
https://github.com/x-cold/yuque-hexo/issues/80#issuecomment-761960251

**Comment by Leader755** [comment]
> > 我这也有同样的问题,将concurrency改为1都不行（叹气
> > 在源代码库里保存语雀文章治标不治本...假如我在语雀新建了一篇很长的文章呢...
> > 如果是语雀那边的问题的话...目前我能想到的解决方案就是支持自定义timeout...或者加入失败重试机制
> > @x-cold 希望前辈能够修复这个问题（鞠躬
> > 作者给了解决方案，可以参考这个，提交PR修复
> > [#80 (comment)](https://github.com/x-cold/yuque-hexo/issues/80#issuecomment-761960251)

可以重试解决吧，目前我就是这样的。不然没办法处理的。至少目前没办法处理的

**Comment by lonbaw** [comment]
> > > 我这也有同样的问题,将concurrency改为1都不行（叹气
> > > 在源代码库里保存语雀文章治标不治本...假如我在语雀新建了一篇很长的文章呢...
> > > 如果是语雀那边的问题的话...目前我能想到的解决方案就是支持自定义timeout...或者加入失败重试机制
> > > @x-cold 希望前辈能够修复这个问题（鞠躬
> > > 作者给了解决方案，可以参考这个，提交PR修复
> > > [#80 (comment)](https://github.com/x-cold/yuque-hexo/issues/80#issuecomment-761960251)
> 
> 可以重试解决吧，目前我就是这样的。不然没办法处理的。至少目前没办法处理的

![image](https://user-images.githubusercontent.com/26515610/116779955-dedbac00-aaab-11eb-8b90-9837e8a5d1e1.png)
我在本地修改测试了下，直接加参数timeout就可以解决这个问题。
我测试是timeout:2 ,直接复现。可以设置为timeout:2000

**Comment by x-cold** [comment]
1.8.0 版本我暂时移除了 @yuque/sdk 的依赖，避免大家遇到 timeout 无法配置的问题
