### ISSUE TITLE
github 的 actions 执行失败能重试吗

### ISSUE THREAD

**Issue by Leader755** [x-cold/yuque-hexo#81]
yuque-hexo sync不定时的会执行超时，那么能不能在执行失败自动重试呢。新手报到，有没有大佬知道的，actions 相关的自动重试的，表示不太会写。或者给指导文档，感谢。

**Comment by Leader755** [comment]
已经找到了方法。

**Comment by xiaolianguu** [comment]
分享一下你的方法呗
