### ISSUE TITLE
加入对Vercel的支持

### ISSUE THREAD

**Issue by MCSeekeri** [x-cold/yuque-hexo#82]
目前的部署方案大多集中在Github Action相关,而Github Action目前还无法部署到Vercel,所以能否添加对Vercel的支持

Vercel会在Repo更新时自动部署,或者调用API以启动部署,似乎没有类似Github Pages的纯静态站点设置
Vercel自带了Serverless函数,也许能用上

[官方的API文档](https://vercel.com/docs/api)

**Comment by x-cold** [comment]
#83

**Comment by MCSeekeri** [comment]
似乎这个只是使用Vercel触发...能不能直接部署到Vercel啊（思考
