### ISSUE TITLE
希望能支持图片镜像~

### ISSUE THREAD

**Issue by shapl** [x-cold/yuque-hexo#85]
图片存储放在语雀，貌似还没有批量打包下载备份的功能。万一哪天防盗链，博客图片就全挂了。
所以希望可以通过七牛或者cos、oss镜像同步的方法，同步语雀文章时，自动替换图片路径。

例如：
https://cdn.nlark.com/yuque/0/2021/png/98805/1616686662636-49299bf3-ee91-4b7d-b7df-3c29d8514afa.png
https://镜像域名/yuque/0/2021/png/98805/1616686662636-49299bf3-ee91-4b7d-b7df-3c29d8514afa.png

**Comment by x-cold** [comment]
欢迎 MR 哈，建议在 adapter 实现这部分逻辑

**Comment by x-cold** [comment]
1.8.0 已经支持自定义 adapter，可以在自己的项目中去实现相关代码呢

实例：https://github.com/x-cold/yuque-hexo/tree/master/test/custom-adapter-project
参考这个实现：https://juejin.cn/post/6875192087705288718

**Comment by shapl** [comment]
> 1.8.0 已经支持自定义 adapter，可以在自己的项目中去实现相关代码呢
> 
> 实例：https://github.com/x-cold/yuque-hexo/tree/master/test/custom-adapter-project
> 参考这个实现：https://juejin.cn/post/6875192087705288718

npm这里还没更新~
https://www.npmjs.com/package/yuque-hexo

**Comment by LetTTGACO** [comment]
https://github.com/LetTTGACO/yuque-hexo-with-cdn

可以看看我写的这个方案，自动上传到腾讯云COS并替换语雀图片

**Comment by x-cold** [comment]
v1.9.0 已支持
