### ISSUE TITLE
希望能在获取文章的时候,把图片下载到本地

### ISSUE THREAD

**Issue by imleft** [x-cold/yuque-hexo#86]
语雀图片防盗链,下载到本地最保险

**Comment by x-cold** [comment]
1.8.0 已经支持自定义 adapter，可以在自己的项目中去实现相关代码呢

实例：https://github.com/x-cold/yuque-hexo/tree/master/test/custom-adapter-project
参考这个实现：https://juejin.cn/post/6875192087705288718

**Comment by LetTTGACO** [comment]
https://github.com/LetTTGACO/yuque-hexo-with-cdn

可以看看我写的这个方案，自动上传到腾讯云COS并替换语雀图片

**Comment by LetTTGACO** [comment]
升级 到1.9.0版本即可，目前支持腾讯云/阿里云/七牛云图床

**Comment by imleft** [comment]
> 升级 到最新版本即可，目前支持腾讯云/阿里云/七牛云图床

如果能用本地就好了.用对象存储虽然有免费额度,难免被刷.

**Comment by LetTTGACO** [comment]
> > 升级 到最新版本即可，目前支持腾讯云/阿里云/七牛云图床
> 
> 如果能用本地就好了.用对象存储虽然有免费额度,难免被刷.

你的意思是把图片直接下载到本地？也可以，但是不推荐。
1、因为图片属于静态资源，如果下载到本地并部署到服务器的话，占用服务器空间资源始终是个定时炸弹。
2、OSS、七牛云等图床的解决方案几乎所有大小公司都在用，已经非常成熟了，防刷防盗都可以进行配置。
3、按照博客的用量来说，OSS的收费几乎可以忽略，我每个月的费用大概不到1毛（毕竟小破站）

**Comment by imleft** [comment]
> > > 升级 到最新版本即可，目前支持腾讯云/阿里云/七牛云图床
> > 
> > 
> > 如果能用本地就好了.用对象存储虽然有免费额度,难免被刷.
> 
> 你的意思是把图片直接下载到本地？也可以，但是不推荐。 1、因为图片属于静态资源，如果下载到本地并部署到服务器的话，占用服务器空间资源始终是个定时炸弹。 2、OSS、七牛云等图床的解决方案几乎所有大小公司都在用，已经非常成熟了，防刷防盗都可以进行配置。 3、按照博客的用量来说，OSS的收费几乎可以忽略，我每个月的费用大概不到1毛（毕竟小破站）

因为全站静态,我现在是放在CF pages,全部走CF比较好,国内OSS域名还要备案,每月出几毛钱的账单心里也不舒服,或者加上国外的比如B2等带宽联盟更好
