### ISSUE TITLE
Unknown command 'yuque-hexo'

### ISSUE THREAD

**Issue by bluesh** [x-cold/yuque-hexo#9]
执行完`npm i --save-dev yuque-hexo`成功安装，但依然报
```
Unknown command 'yuque-hexo'
```
nodejs版本7.7.0
可能是什么原因？

**Comment by x-cold** [comment]
默认安装是在当前项目的 node_moduels 目录下，

0、执行 node_modules/.bin/yuque-hexo sync

1、全局安装 yuque-hexo

```
npm i -g yuque-hexo
```

2、使用 npx 或者 npm script 来执行 yuque-hexo

在你的 package.json 中添加如下，然后 npm run sync。
```
{
  "script": {
    "sync": "yuque-hexo sync"
  }
}
```
