### ISSUE TITLE
hexo-butterfly博客使用插件时，font-matter部分图片自动渲染成网页的问题

### ISSUE THREAD

**Issue by MINTPlanetarian** [x-cold/yuque-hexo#90]
大佬好，首先很感谢您开发了这个插件，但今天在使用您的插件做自动部署时，发现在语雀平台存放的Markdown文件的font-matter部分中的图片，在拉到本地后，会被自动渲染为网页，导致图片不能正常显示。请问大佬这个问题怎么解决？还是是因为插件的渲染问题导致的？如图：
![](https://img.bolun.xyz/20210711171849.png)
![](https://img.bolun.xyz/20210711172010.png)

**Comment by Conroy-X** [comment]
你的图片上传到 语雀， 他把你的图片放到她的CND里边去了， 然后把你图片转成了你图片在cdn的链接了

是这样的

**Comment by MINTPlanetarian** [comment]
> 你的图片上传到 语雀， 他把你的图片放到她的CND里边去了， 然后把你图片转成了你图片在cdn的链接了
> 
> 是这样的

那请问应该怎么解决这个问题呢

**Comment by Conroy-X** [comment]
我认为可以这样：
      格式化文章的时候， 通过正则匹配语雀的链接， 下载到本地， 再把之前的匹配的链接换成本地的地址(或者用jsDelivr的链接)

**Comment by x-cold** [comment]
1.8.0 已经支持自定义 adapter，可以在自己的项目中去实现相关代码呢

实例：https://github.com/x-cold/yuque-hexo/tree/master/test/custom-adapter-project

**Comment by x-cold** [comment]
v1.9.0 已支持图片转存，欢迎升级使用
