### ISSUE TITLE
yuque-hexo sync报错

### ISSUE THREAD

**Issue by nanakura** [x-cold/yuque-hexo#97]
![image](https://user-images.githubusercontent.com/69560752/143528085-8a7a5137-5e9e-4bb4-a586-6e44e3846135.png)

**Comment by zy84338719** [comment]
这个问题 是因为文章不规范导致的 老的文章格式需要更改 我的解决办法 重新创建文章 可以过
或者在源代码增加download处理 就没有这个问题了

**Comment by zy84338719** [comment]
try catch

**Comment by x-cold** [comment]
可以 MR 一下
